version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    environment:
      DATABASE_URL: postgresql://${PIPELINE_DB_USER}:${PIPELINE_DB_PASSWORD}@${PIPELINE_DB_HOST}:${PIPELINE_DB_PORT}/${PIPELINE_DB_NAME}
      PIPELINE_DATA_DIR: /opt/pipeline/data/raw
      DEFAULT_CHUNK_SIZE: 5
    volumes:
      - ./app:/opt/pipeline
      - ./data:/opt/pipeline/data
    depends_on:
      - postgres

  jupyter:
    image: jupyter/minimal-notebook
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
    ports:
      - "8888:8888"
    command: start-notebook.sh --NotebookApp.default_url=/lab/tree/0_START_HERE.ipynb
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

volumes:
  postgres_data:
